apiVersion: apps/v1
kind: Deployment
metadata:
  name: jhooq-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jhooq-springboot
  template:
    metadata:
      labels:
        app: jhooq-springboot
    spec:
      containers:
        - name: springboot
          image: vogetisameer12/jhooq-docker-demo:jhooq-docker-demo
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: jhooq-springboot
spec:
  ports:
  - name: http
    targetPort: 8080
    port: 8080
  selector:
    app: jhooq-springboot
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jhooq-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: oam.cluster-01.company.com
    http:
      paths:
      - path: /jhooq
        backend:
          serviceName: jhooq-springboot
          servicePort: http
    
